.TH "assign" 1 "February 1, 2024" "Escalante-Notario, Perez-Martinez, Ramos-Sanchez and Vaudrevange"


.SH NAME

assign

.SH SYNOPSIS
.B assign [OPTIONS]

.SH DESCRIPTION
This command assigns a new label to the fixed point/brane with localization (k,m,n,n1,n2,n3,n4,n5,n6).

.SH OPTIONS
.TP
.B label(Label) to fixed point(k,m,n,n1,n2,n3,n4,n5,n6)


It assigns the label 'Label' to the fixed point/brane with localization (k,m,n,n1,n2,n3,n4,n5,n6).

.SH EXAMPLES

\(bu Consider the Z3 orbifold model named Z3_1_1. The following command assigns the Label 'Z' to the fixed point with localization (0,2,0,0,1,0,0,0,0)

.B assign label(Z) to fixed point(0,2,0,0,1,0,0,0,0)

First, we give some previous information to know the label that is changed. The command 'print all states' in the spectrum directory lists the currently labels associated to the fixed point/brane with localization (k,m,n,n1,n2,n3,n4,n5,n6). For example, a part of the corresponding output reads, 

  /Z3_1_1/spectrum/> print all states

   ...

  =========================================================================
    (0, 2, 0) twisted Sector (0, 2, 0) (    0,     1,     0,     0,     0,     0)
    label: T31
  -------------------------------------------------------------------------
      1 ( 10,  1,  1)_s  U(1) : (  -24)  s_22 
      1 (  1,  1,  1)_s  U(1) : (   48)  s_23 
  -------------------------------------------------------------------------

 ...

where ... indicates additional information (see the man help in the spectrum directory by typing man print, then look for 'print all states'). The label associated with the fixed point with localization (k,m,n,n1,n2,n3,n4,n5,n6) = (0, 2, 0, 0, 1, 0, 0, 0, 0) is T31. This is the label that is changed with the command 'assign label(Z) to fixed point(0,2,0,0,1,0,0,0,0)' in the labels directory. Note that different fields can be associated with the same localization for the fixed point, i.e. with the same label. In this case, for the Z3 orbfifold, the fields labeled as s_22, s_23, s_24, s_25, s_26 and f_10 have the same fixed point localization (k,m,n,n1,n2,n3,n4,n5,n6) = (0, 2, 0, 0, 1, 0, 0, 0, 0), i.e. the same label T31. 

Now, the use of the command 'assign label(Z) to fixed point(0,2,0,0,1,0,0,0,0)' in the prompt and the corresponding output reads, 

  /Z3_1_1/vev-config/labels/> assign label(Z) to fixed point(0,2,0,0,1,0,0,0,0)

    Label "Z" assigned to fixed point (0, 2, 0) (    0,     1,     0,     0,     0,     0)).


Then, the use of the command 'print all states' in the spectrum directory displays the corresponding information where now the label for the fixed point with localization (k,m,n,n1,n2,n3,n4,n5,n6) = (0, 2, 0, 0, 1, 0, 0, 0, 0) is Z. This change applies for the fields labeled as s_22, s_23, s_24, s_25, s_26 and f_10, since all of them share the same localization. In the prompt the output reads, for example,


  /Z3_1_1/spectrum/> print all states

  ...

  =========================================================================
    (0, 2, 0) twisted Sector (0, 2, 0) (    0,     1,     0,     0,     0,     0)
    label: Z
  -------------------------------------------------------------------------
      1 ( 10,  1,  1)_s  U(1) : (  -24)  s_22 
      1 (  1,  1,  1)_s  U(1) : (   48)  s_23 
  -------------------------------------------------------------------------

  ... 

where the new assigned label Z appears explicitly.

\(bu Other examples for the command 'assign label(Label) to fixed point(k,m,n,n1,n2,n3,n4,n5,n6)' follow a similar treatment as the example shown above.  

NOTE. An explanation for the notation (k,m,n,n1,n2,n3,n4,n5,n6) is provided in the spectrum directory by typing man print.


.SH AUTHOR
E. Escalante-Notario, R. Perez-Martinez, S. Ramos-Sanchez and P.K.S. Vaudrevange

.SH SEE ALSO
Related here article, additional documentation.

.SH REPORTING BUGS
Reporting bugs and problems, in this link https://github.com/enriqueescalante/Orbifolder_N-0/issues/new

.SH VERSION
1.0
