.TH "print" 1 "February 1, 2024" "Escalante, Perez, Ramos and Vaudrevange"

.SH NAME
print 

.SH SYNOPSIS
.B print [options]

.SH DESCRIPTION
This command prints information about the orbifold geometry. 

.SH OPTIONS
.TP
.B orbifold label
.TP 
.B heterotic string type
.TP 
.B available space groups
.TP
.B point group
.TP
.B space group
.TP
.B twist
.TP
.B #SUSY
.TP 
.B shift
.TP
.B Wilson lines


.SH EXAMPLES
The following command prints the available space groups.

.B print available space groups

The following command prints the Wilson lines (WLs), identified WLs and their allowed orders.

.B print Wilson lines

The following command prints the twist vector

.B print twist

For example, the user will see  v_1 = (    0,   1/3,   1/3,  -2/3) for the Z3 orbifold.




.SH AUTHOR
E. Escalante-Notario, R. Perez-Martinez, S. Ramos-Sanchez and P.K.S. Vaudrevange

.SH SEE ALSO
Related here article, additional documentation.

.SH REPORTING BUGS
Reporting bugs and problems, in this link https://github.com/enriqueescalante/Orbifolder_N-0/issues/new

.SH VERSION
1.0
