.TH "print" 1 "February 1, 2024" "Enrique Escalante-Notario"

.SH NAME
print - Print information about orbifold

.SH SYNOPSIS
.B print [options]

.SH DESCRIPTION
This command prints information about orbifold's features. For example
the space groups that are available.

.SH OPTIONS
.TP
.B available space groups
Print details about available space groups.
.TP
.B print orbifold label
.TP 
.B print heterotic string type
.TP 
.B print available space groups
.TP
.B print point group
.TP
.B print space group
.TP
.B print twist
.TP
.B print #SUSY
.TP 
.B print shift
.TP
.B print Wilson lines


.SH EXAMPLES
The following command prints general information about available space groups:
.EX
print available space groups
.EE


.SH AUTHOR
Enrique Escalante-Notario

.SH SEE ALSO
Related manuals, additional documentation.

.SH HISTORY
Date and details of previous versions.

.SH NOTES
Additional information or important considerations.

.SH BUGS
List of known issues or bugs.

.SH COPYRIGHT
Copyright © Year, Your Company

.SH ACKNOWLEDGMENTS
Acknowledgments to individuals or resources that contributed to the development.

.SH REPORTING BUGS
Instructions for reporting bugs.

.SH VERSION
Current version number of the command.
