.TH "set" 1 "February 1, 2024" "Enrique Escalante-Notario"

.SH NAME
set - Allows defining some configurations of the orbifold.

.SH SYNOPSIS
.B set [OPTIONS]

.SH DESCRIPTION
This command prints information about available space groups. If the option
available space groups is provided, it will print details specifically about available space groups.

.SH OPTIONS
.TP
.B available space groups
Print details about available space groups.

.SH EXAMPLES
The following command prints general information about available space groups:
.EX
print available space groups
.EE


.SH AUTHOR
Enrique Escalante-Notario

.SH SEE ALSO
Related manuals, additional documentation.

.SH HISTORY
Date and details of previous versions.

.SH NOTES
Additional information or important considerations.

.SH BUGS
List of known issues or bugs.

.SH COPYRIGHT
Copyright © Year, Your Company

.SH ACKNOWLEDGMENTS
Acknowledgments to individuals or resources that contributed to the development.

.SH REPORTING BUGS
Instructions for reporting bugs.

.SH VERSION
Current version number of the command.
