.TH "print" 1 "February 1, 2024" "Escalante, Perez, Ramos and Vaudrevange"

.SH NAME
print - Print information about available space groups.

.SH SYNOPSIS
.B print available space groups

.SH DESCRIPTION
This command prints information about available space groups. If the option
available space groups is provided, it will print details specifically about available space groups.

.SH OPTIONS
.TP
.B available space groups
Print details about available space groups.

.SH EXAMPLES
The following command prints general information about available space groups:
.EX
print available space groups
.EE


.SH AUTHOR
E. Escalante-Notario, R. Perez-Martinez, S. Ramos-Sanchez and P.K.S. Vaudrevange

.SH SEE ALSO
Related here article, additional documentation.

.SH REPORTING BUGS
Reporting bugs and problems, in this link https://github.com/enriqueescalante/Orbifolder_N-0/issues/new

.SH VERSION
1.0

