.TH "print" 1 "February 1, 2024" "Escalante-Notario, Perez-Martinez, Ramos-Sanchez and Vaudrevange"

.SH NAME
print 

.SH SYNOPSIS
.B print [OPTIONS]

.SH DESCRIPTION

This command prints the vev-configurations and gauge group for the orbifold model.


.SH OPTIONS
.TP
.B configs

It prints a list of vev-configurations defined for the orbifold model. The currently vev-configuration is indicated by an arrow.
  
.TP
.B gauge group

It prints the gauge group for the selected choice of observable and hidden sector of the currently used vev-configuration. Gauge group factors that belong to the hidden are in brackets.


.SH EXAMPLES
\(bu The following command prints a list of vev-configurations defined for the orbifold model.  

.B print configs

- An explicit example is the following. Consider the Z3 orbifold model named Z3_1_1. The use of this command in the prompt and the output reads, for example,

  /Z3_1_1/vev-config/> print configs

    list of vev-configurations: 
       label             | field label # |
      -------------------------------------- 
       "StandardConfig1" |        1 /  1 | 
    -> "TestConfig1"     |        1 /  1 | 


- Consider now a SM-like model named Model_SM3 in the vev-configuration SMConfig1. The use of the command 'print configs' in the prompt and the output reads, for example,

  /Model_SM3/vev-config/> print configs

    list of vev-configurations: 
       label             | field label # |
      -------------------------------------- 
       "StandardConfig1" |        1 /  1 | 
       "TestConfig1"     |        1 /  1 | 
    -> "SMConfig1"       |        2 /  2 | 

The fractions on the second column indicate the i-th labeling of the fields that is currently used.  


\(bu The following command prints the gauge group of the orbifold model for the selected choice of observable and hidden sector of the currently used vev-configuration

.B print gauge group

- As an example consider the Z3 orbifold model named Z3_1_1. The use of this command in the prompt and the output reads, 

  /Z3_1_1/vev-config/> print gauge group

    Gauge group in vev-configuration "TestConfig1": SO(10) x SU(3) and SO(16) and U(1)_1


- Another example is the following. Consider a SM-like model named Model_SM3 in the vev-configuration SMConfg1. The use of this command in the prompt and the corresponding output reads, for example, 

  /Model_SM3/vev-config/> print gauge group

    Gauge group in vev-configuration "SMConfig1": SU(3)_C x SU(2)_L x [SU(2)] and [SU(3)] and [U(1)_1] x U(1)_2,Y x [U(1)_3] x [U(1)_4] x [U(1)_5] x [U  (1)_6] x [U(1)_7] x [U(1)_8] x [U(1)_9] x [U(1)_10]

    (factors in brackets, e.g. [SU(2)], belong to the hidden sector in this vev-configuration)

The observable sector, which in this case is the Standard model gauge group, can be changed with the command 'select observable sector: parameters'. See 'man select' for a brief explanation.  



.SH AUTHOR
E. Escalante-Notario, R. Perez-Martinez, S. Ramos-Sanchez and P.K.S. Vaudrevange

.SH SEE ALSO
Related here article, additional documentation.

.SH REPORTING BUGS
Reporting bugs and problems, in this link https://github.com/enriqueescalante/Orbifolder_N-0/issues/new

.SH VERSION
1.0

