.TH "load" 1 "February 1, 2024" "Enrique Escalante-Notario"

.SH NAME
load - Load orbifolds from a specified file.

.SH SYNOPSIS
.B load orbifolds(Filename)

.SH DESCRIPTION
This command loads orbifolds from the specified file (Filename) into the current environment.

.SH OPTIONS
.TP
.B orbifolds(Filename)
Specifies the file from which orbifolds will be loaded.

.SH EXAMPLE
The following command loads orbifolds from a file named "example.orb":
.EX
load orbifolds(example.orb)
.EE

.SH AUTHOR
Enrique Escalante-Notario

.SH SEE ALSO
Related manuals, additional documentation.

.SH HISTORY
Date and details of previous versions.

.SH NOTES
Additional information or important considerations.

.SH BUGS
List of known issues or bugs.

.SH COPYRIGHT
Copyright © Year, Your Company

.SH ACKNOWLEDGMENTS
Acknowledgments to individuals or resources that contributed to the development.

.SH REPORTING BUGS
Instructions for reporting bugs.

.SH VERSION
Current version number of the command.
