.TH "create" 1 "February 1, 2024" "Escalante, Perez, Ramos and Vaudrevange"


.SH NAME
create 

.SH SYNOPSIS
.B create [OPTIONS]

.SH DESCRIPTION
This command creates random orbifolds with point group ZM x ZN. It allows the use of several useful parameters.

.SH OPTIONS

.B "orbifold(OrbifoldLabel) with point group(M,N)"
    This command creates an orbifold named OrbifolLabel with point group ZM x ZN. For ZM set N=1. The model is stored in the directory 
    OrbifolLabel and after entering it, additional details of the model like the shifts and Wilson lines are required to enter. 

.B "create orbifold(OrbifoldLabel) from(AnotherOrbifoldLabel)
    This command creates an orbifold model named OrbifoldLabel from another existing orbifold model (previously loaded or created) called 
    AnotherOrbifoldLabel. The new created model is equal to AnotherOrbifoldLabel, they differ in their names. 

.B "random orbifold from(OrbifoldLabel)" 
    This commands creates a random orbifold from an existing orbifold model (previously loaded or created) named OrbifolLabel. It can be 
    complemented with the following parameters:

\(bu if(...)

It indicates properties of the models to look for: SM, PS, SU5, and inequivalent.

\(bu save to(Filename)

It saves the orbifold models in a text file named Filename.

\(bu use(1,0,0,0,0,0,0,1)

The first two digits are for the shifts, the remaining digits are for the six Wilson Lines. 0 indicates that the shifts and Wilson lines are created randomly. 1 indicates that they are taken from the original OrbifoldLabel. 

\(bu print info

It prints a summary of the spectrum for the randomly created models.

\(bu #models(X)

It creates a number of X random models with the specified properties. To create as many as possible use X = all. 

\(bu load when done

After completing the creation of the models, this command loads the models. 

\(bu do not check anomalies

It speeds up the search and creation of the orbifold models with the specified properties.


.SH EXAMPLES
The following command creates an orbifold named orbi1 with point group Z3 x Z3.

.B create orbifold(orbi1) with point group(3,3)

After entering the directory, cd orbi1, additional details of the model like the shifts and Wilson lines need to be specified. 


The following command creates ten random orbifolds from the Z3_1_1 orbifold model. They are required to be SM-like and inequivalent. The models
are saved in the file tenmodels.txt and all Wilson lines and shifts are created randomly. After the process is complete, these models
are loaded, each of them is stored in one directory named Model_SM1, ..., Model_SM10.

.B create random orbifold from(Z3_1_1) if(inequivalent SM) save to(tenmodels.txt) use(0,0,0,0,0,0,0,0) load when done #models(10)

The following command creates five random orbifold models from the Z3_1_1 orbifold. The models are saved in a file models.txt, the shift and the third and fourth Wilson lines are taken from the original model, while the other Wilson lines are created randomly. A summary of the spectrum is printed, and after the process is finished, the five models are loaded and stored in directories named Random1, ..., Random5. 

.B create random orbifold from(Z3_1_1) save to(models.txt) use(1,0,0,0,1,1,0,0) load when done #models(5) print info


.SH AUTHOR
E. Escalante-Notario, R. Perez-Martinez, S. Ramos-Sanchez and P.K.S. Vaudrevange

.SH SEE ALSO
Related here article, additional documentation.

.SH REPORTING BUGS
Reporting bugs and problems, in this link https://github.com/enriqueescalante/Orbifolder_N-0/issues/new

.SH VERSION
1.0
