.TH "delete" 1 "February 1, 2024" "Escalante, Perez, Ramos and Vaudrevange"

.SH NAME
delete - Delete orbifolds.

.SH SYNOPSIS
.B delete orbifold(OrbifoldLabel)

.SH DESCRIPTION
This command deletes the orbifold with the specified name (OrbifoldLabel), and it is also capable of deleting all loaded orbifolds

.SH OPTIONS
.TP
.B orbifold(OrbifoldLabel)
Specifies the orbifold that will be deleted.


.TP
.B orbifolds
All orbifolds are deleted


.SH EXAMPLE
The following command deletes the orbifold named ExampleOrbifold.

.EX
cd ExampleOrbifold
.EE

.SH AUTHOR
E. Escalante-Notario, R. Perez-Martinez, S. Ramos-Sanchez and P.K.S. Vaudrevange

.SH SEE ALSO
Related here article, additional documentation.

.SH REPORTING BUGS
Reporting bugs and problems, in this link https://github.com/enriqueescalante/Orbifolder_N-0/issues/new

.SH VERSION
1.0
