.TH "save" 1 "February 1, 2024" "Enrique Escalante-Notario"

.SH NAME
save - Save orbifolds to a specified file.

.SH SYNOPSIS
.B save orbifolds(Filename)

.SH DESCRIPTION
This command saves the current orbifolds to the specified file (Filename).

.SH OPTIONS
.TP
.B orbifolds(Filename)
Specifies the file to which the current orbifolds will be saved.

.SH EXAMPLE
The following command saves the current orbifolds to a file named "output.orb":
.EX
save orbifolds(output.orb)
.EE

.SH AUTHOR
Enrique Escalante-Notario

.SH SEE ALSO
Related manuals, additional documentation.

.SH HISTORY
Date and details of previous versions.

.SH NOTES
Additional information or important considerations.

.SH BUGS
List of known issues or bugs.

.SH COPYRIGHT
Copyright © Year, Your Company

.SH ACKNOWLEDGMENTS
Acknowledgments to individuals or resources that contributed to the development.

.SH REPORTING BUGS
Instructions for reporting bugs.

.SH VERSION
Current version number of the command.
