.TH "print" 1 "February 1, 2025" "Escalante-Notario, Perez-Martinez, Ramos-Sanchez and Vaudrevange"

.SH NAME
print

.SH SYNOPSIS
.B print [OPTIONS]

.SH DESCRIPTION
This command prints information about the gauge group, the beta coefficients, the simple roots, anomalies, B-L generator and U1 generators.

.SH OPTIONS
.TP
.B gauge group 

It prints the four-dimensional gauge group in the current vev-configuration.

.TP
.B beta coefficients

It shows the non-supersymmetric beta coefficients at one-loop for the non-Abelian gauge groups in the observable sector of the four-dimensional gauge group. It also prints the current vev-configuration. 

.TP
.B simple roots

It prints a choice of simple roots as 16D vectors for the non-Abelian gauge groups. The number of simple roots corresponds to the rank of the non-Abelian gauge group factors contained in the full 4D gauge group.

.TP
.B simple root(i)

It shows the i-th simple root as a 16D vector. The index i can be any number between 1 and n, where n is the total number of simple roots. 

.TP
.B anomaly info

It displays information about the gauge and gravitational anomalies and verify their universality relations.

.TP
.B B-L generator

It prints the B-L generator as a 16D vector, which was previously introduced with the command set B-L = <16D vector>. See man set, for example. 
 

.TP
.B U1 generators 

It shows all U(1) generators as 16D vectors.                      

.TP
.B U1 generator(i)

It prints the i-th U(1) generator as a 16D vector.

.SH EXAMPLES

\(bu For the Z3_1_1 orbifold model, the following command prints the gauge group and the current vev-configuration.

.B print gauge group

The output reads

  Gauge group in vev-configuration "TestConfig1": SO(10) x SU(3) and SO(16) and U(1)_1


\(bu Consider a SM-like model in the orbifold geometry Z3xZ3 (1,1) and in the vev-configuration SMConfig1. In this case the output reads, for example,

  Gauge group in vev-configuration "SMConfig1": SU(3)_C x SU(2)_L x [SU(2)] and [SU(3)] and [U(1)_1] x U(1)_2,Y x [U(1)_3] x [U(1)_4] x [U(1)_5] x [U(1)_6] x [U(1)_7] x [U(1)_8] x [U(1)_9] x [U(1)_10]

where gauge group factors in brackets belong to the hidden sector and the others consitute the observable sector, which in this case is the SM gauge group SU(3)_C x SU(2)_L x U(1)_2,Y.  


\(bu Consider the Z3_1_1 orbifold model, the following command 

.B print beta coefficients

shows the non-supersymmetric beta coefficients at one loop for the non-Abelian gauge groups. The output reads, for example,

  Beta function coefficients in vev-configuration "TestConfig1" (N = 0 SUSY):
    b_{SO(10)} = 44/1
    b_{SU(3)} = 40/1
    b_{SO(16)} = -10/1

\(bu For a SM-like model in the orbifold geometry Z3xZ3 (1,1) (presented previously as the second example of 'print gauge group'), the outputs reads, for example,

  Beta function coefficients in vev-configuration "SMConfig1" (N = 0 SUSY):
    b_{SU(3)_C} = 65/6
    b_{SU(2)_L} = 19/2

Note that the beta coefficients are calculated for the non-Abelian gauge groups of the observable sector in the current vev-configuration. The gauge groups in the observable sector can be changed by using the command 'select observable sector' in the vev-config directory.


\(bu Consider the Z3_1_1 orbifold model. The gauge group is SO(10)xSU(3)xSO(16)xU(1). The following command displays a choice of simple roots for the non-Abelian group factors

.B print simple roots

The output reads, for example,

  Simple roots:
    (    0,     0,     0,     1,    -1,     0,     0,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)
    (    0,     0,     0,     0,     1,    -1,     0,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)
    (    0,     0,     0,     0,     0,     1,    -1,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)
    (    0,     0,     0,     0,     0,     0,     1,     1),  (    0,     0,     0,     0,     0,     0,     0,     0)
    (    0,     0,     0,     0,     0,     0,     1,    -1),  (    0,     0,     0,     0,     0,     0,     0,     0)
    (    0,     1,    -1,     0,     0,     0,     0,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)
    (    1,    -1,     0,     0,     0,     0,     0,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)
    (    0,     0,     0,     0,     0,     0,     0,     0),  (    1,    -1,     0,     0,     0,     0,     0,     0)
    (    0,     0,     0,     0,     0,     0,     0,     0),  (    0,     1,    -1,     0,     0,     0,     0,     0)
    (    0,     0,     0,     0,     0,     0,     0,     0),  (    0,     0,     1,    -1,     0,     0,     0,     0)
    (    0,     0,     0,     0,     0,     0,     0,     0),  (    0,     0,     0,     1,    -1,     0,     0,     0)
    (    0,     0,     0,     0,     0,     0,     0,     0),  (    0,     0,     0,     0,     1,    -1,     0,     0)
    (    0,     0,     0,     0,     0,     0,     0,     0),  (    0,     0,     0,     0,     0,     1,    -1,     0)
    (    0,     0,     0,     0,     0,     0,     0,     0),  (    0,     0,     0,     0,     0,     0,     1,     1)
    (    0,     0,     0,     0,     0,     0,     0,     0),  (    0,     0,     0,     0,     0,     0,     1,    -1)


In this case there are fifteen simple roots since the rank of SO(10)xSU(3)xSO(16) is 5+2+8=15. 


\(bu The following commmand prints the third simple root of the previous set

.B print simple root(3)

and the output reads,

  simple root (3):
    (    0,     0,     0,     0,     0,     1,    -1,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)


\(bu The following command prints details for the gauge and gravitational anomalies. It also checks their universality relations.  

.B prints anomaly info

For the Z3_1_1 orbifold model the output reads, for example,

  SU(N)^3 anomaly:
    2-th gauge group factor A2: tr cubic    = 0/1

  U(1)_i - U(1)_i - U(1)_i, U(1)_i - U(1)_j - U(1)_j and U(1)_i - grav. - grav. anomalies:
    tr Q_1       = 20736/1
    tr Q_1^3     = 8957952/1

  G - G - U(1)_j anomalies for G = SU(N), SO(N) or E_N:
    tr l(rep. of D5) Q_1 = 1728/1
    tr l(rep. of A2) Q_1 = 1728/1
    tr l(rep. of D8) Q_1 = 1728/1

  All anomalies are universal, i.e. their ratios are OK.


\(bu The following command prints all U(1) generators.

.B print U1 generators

For the Z3_1_1 orbifold model the output reads

  U(1) generators:
    (   24,    24,    24,     0,     0,     0,     0,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)  

Here only one U(1) generator is shown since the 4D gauge group is SO(10)xSU(3)xSO(16)xU(1). 

\(bu Now suppose a SM-like model with a 4D gauge group containing ten U(1)s and in the SM vev-configuration (as the second example used in 'print gauge group'). In  this case the output reads, for example,

  U(1) generators:
    ( -5/2,   5/2,   5/2,   5/2,  -5/2,   3/2, -15/2, -15/2),  (   -7,    -1,    -2,     2,     1,     6,     1,    -1)  
    (  1/2,   1/3,   1/3,   1/3,   1/2,     0,     0,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)  Y
    (    3,    -3,    -3,    -3,     3,    25,     0,     0),  (    0,     0,     0,     0,     0,     0,     0,     0)  
    (  -70,    70,    70,    70,   -70,    42,     0,     0),  (  134,     0,     0,     0,     0,     0,     0,     0)  
    (  -10,    10,    10,    10,   -10,     6,     0,     0),  (  -28,   330,     0,     0,     0,     0,     0,     0)  
    (  -20,    20,    20,    20,   -20,    12,     0,     0),  (  -56,    -8,   334,     0,     0,     0,     0,     0)  
    (   20,   -20,   -20,   -20,    20,   -12,     0,     0),  (   56,     8,    16,   350,     0,     0,     0,     0)  
    (   20,   -20,   -20,   -20,    20,   -12,     0,     0),  (   56,     8,    16,   -16,     0,   122,     0,     0)  
    (   -5,     5,     5,     5,    -5,     3,    17,    17),  (  -14,    -2,    -4,     4,     0,    12,     0,     0)  
    (   -5,     5,     5,     5,    -5,     3,   -15,   -15),  (  -14,    -2,    -4,     4,  -160,    12,  -160,   160)  

where the letter Y at the end of the second generator indicates that this generator corresponds to the U(1)_Y hypercharge of the SM. It is
normalized as Y^2 = 5/6 to be compatible with SU(5) grand unification.

\(bu The following command selects the ninth generator of the previous set of ten U(1) generators

.B print U1 generator(9)

and the output reads

  U(1) generator (9):
    (   -5,     5,     5,     5,    -5,     3,    17,    17),  (  -14,    -2,    -4,     4,     0,    12,     0,     0)


.SH AUTHOR
E. Escalante-Notario, R. Perez-Martinez, S. Ramos-Sanchez and P.K.S. Vaudrevange

.SH SEE ALSO
Related here article, additional documentation.

.SH REPORTING BUGS
Reporting bugs and problems, in this link https://github.com/StringsIFUNAM/nonSUSYorbifolder/issues/new

.SH VERSION
1.0

Current version number of the command.
