.TH "print" 1 "February 1, 2024" "Escalante, Perez, Ramos and Vaudrevange"

.SH NAME
print

.SH SYNOPSIS
.B print [OPTIONS]

.SH DESCRIPTION
This command prints information about the gauge group.

.SH OPTIONS
.TP
.B gauge group 
.TP
.B beta coefficients
.TP
.B simple root(i)    
i denotes the i-th simple root
.TP
.B simple roots
.TP
.B anomaly info
.TP
.B B-L generator
.TP
.B U1 generator(i)                     
.TP
.B U1 generators


.SH EXAMPLES
The following command prints the gauge group

.B print gauge group

The following command prints the simple roots

.B print simple roots

.SH AUTHOR
E. Escalante-Notario, R. Perez-Martinez, S. Ramos-Sanchez and P.K.S. Vaudrevange

.SH SEE ALSO
Related here article, additional documentation.

.SH REPORTING BUGS
Reporting bugs and problems, in this link https://github.com/enriqueescalante/Orbifolder_N-0/issues/new

.SH VERSION
1.0

Current version number of the command.
